<?php
return array(
	"add_user" 			=> 'Added New User',
	"modify_user"		=> 'Modified User',
	"change_password"	=> 'Changed Password',
	"delete_user"		=> 'Deleted Users',
	"add_user_role"		=> 'Added New User Role',
	"modify_user_role"	=> 'Modified User Role',
	"delete_user_role"	=> 'Deleted User Roles',
	"add_setting"		=> 'Added New Setting',
	"modify_setting"	=> 'Modifed Settings',
	"delete_settings"	=> "Deleted Settings",
	"assign_po"			=> "Assigned PO",
	"close_po"			=> "Closed PO",
	"post_store_order"	=> 'Put away to dispatching zone',
	"put_to_reserve"	=> 'Put away to reserve zone',
	"assign_to_piler"	=> 'Assign to Stock Piler',
	"modify_po_status"	=> "Update Purchase Order Status",
	"update_po_detail"	=> "Update Purchase Order Detail",
	"save_po"			=> "Save Received PO",
	"post_letdown"		=> 'Put away to picking zone',
	"post_letdown_done"	=> 'Change status of letdown document to done',
	"post_letdown_close"	=> 'Change status of letdown document to closed',
	'post_picklist_to_box'	=> 'Move picklist item to box',
	"unlock_letdown_tag"	=> 'Unlock Letdown Tag',
	"unlock_picklist_tag"	=> 'Unlock Picklist Tag',
	"generate_load_code"	=> 'Generate Load Code',
	"picklist_change_to_store"	=> 'Picklist change type to store',
	"picklist_load"		=> 'Load Picklists',
	"box_load"		=> 'Load Boxes',
	"ship_load"		=> 'Ship load',
	"create_box"		=> "Create Box",
	"update_box"		=> "Update Box",
	"delete_box"		=> "Delete Box",
	"export_boxes"		=> "Export Boxes"
);
