<?php

class SlotSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run() {
	
		DB::table('slot_lists')->truncate();
		  SlotList::create(array(
		    "slot_code"=>"1AOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1AOD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOF11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOF12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOF21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOF22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOF31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1BOF32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COF11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COF12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COF21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COF22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COF31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1COF32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOF11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOF12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOF21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOF22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOF31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1DOF32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOF11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOF12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOF21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOF31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOF32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOA41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOA42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOB41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOB42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOC41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2AOC42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOA41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOA42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOB41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOB42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOC41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOC42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOD41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOD42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOE41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOE42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COA41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COA42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COB41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COB42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COC41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COC42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOD41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOD42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COD41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COD42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COE41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2COE42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOA41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOA42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOB41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOB42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOC41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOC42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOE41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2DOE42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOA41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOA42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOB41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOB42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOC41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOC42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOD41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOD42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOE41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOE42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOF11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOF12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOF21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOF22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOF31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOF32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOF41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOF42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOA41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOA42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOB41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOB42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOC41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3AOC42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOA41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOA42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOB41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOB42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOC41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOC42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOD41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOD42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOE41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOE42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COA41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COA42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COB41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COB42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COC41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COC42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COD41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COD42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COE41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3COE42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOA11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOA12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOA31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOA41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOA42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOA21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOA32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOB11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOB12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOB31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOB32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOB41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOB42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOC11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOC12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOC21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOC22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOC31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOC32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOC41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOC42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOD11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOD12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOD21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOD22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOD31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOD32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOD41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOD42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOE11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOE12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOE21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOE22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOE31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOE32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOE41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOE42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOF11"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOF12"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOF21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOF22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOF31"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOF32"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOF41"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3DOF42"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"1EOF22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2EOA22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"3BOB22"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"2BOB21"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"RZ000001"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"PCK00001"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"SZ000001"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"LOST"
		  ));
		  SlotList::create(array(
		    "slot_code"=>"NGM0001"
		  ));
	}

}