<?php

class ApiLoads extends BaseController {


	public function __construct() {
		date_default_timezone_set('Asia/Manila');
	}

	/**
	* Generate Load Code
	*
	* @example  www.example.com/api/{version}/boxes/create/load
	*
	* @return load code
	*/
	public function generateLoadCode()
	{
		try {
			DB::beginTransaction();

			$loadMax =  Load::select(DB::raw('max(id) as max_created, max(load_code) as load_code'))->first()->toArray();

			if($loadMax['max_created'] === null) {
				$loadCode = 'LD0000001';
			} else {
				$loadCode = substr($loadMax['load_code'], -7);
				$loadCode = (int) $loadCode + 1;
				$loadCode = 'LD' . sprintf("%07s", (int)$loadCode);
			}

			Load::create(array('load_code'	=> $loadCode));

			self::generateLoadCodeAuditTrail($loadCode);

			DB::commit();
			return CommonHelper::return_success_message($loadCode);
		} catch (Exception $e) {
			DB::rollback();
			return CommonHelper::return_fail($e->getMessage());
		}
	}

	/**
	* Audit trail for generating load code
	*
	* @example  self::generateLoadCodeAuditTrail()
	*
	* @param  $loadCodeload code
	* @return void
	*/
	private function generateLoadCodeAuditTrail($loadCode)
	{
		$user_id = Authorizer::getResourceOwnerId();
		$userInfo = User::find($user_id);
		$data_after = 'Load code # '.$loadCode . ' generated by ' . $userInfo->username;
		$arrParams = array(
			'module'		=> Config::get("audit_trail_modules.picking"),
			'action'		=> Config::get("audit_trail.generate_load_code"),
			'reference'		=> 'Load code # ' . $loadCode,
			'data_before'	=> '',
			'data_after'	=> $data_after,
			'user_id'		=> $user_id,
			'created_at'	=> date('Y-m-d H:i:s'),
			'updated_at'	=> date('Y-m-d H:i:s')
		);
		AuditTrail::addAuditTrail($arrParams);
	}

	public function getList() {
		try {
			$loads = Load::getLoads();

			return CommonHelper::return_success_message($loads);
		} catch (Exception $e) {
			return CommonHelper::return_fail($e->getMessage());
		}
	}


}